wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1661906419.670593
    t:
      1:
      - 1
      - 5
      - 41
      - 50
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 50
      - 53
      - 55
      - 63
      3:
      - 1
      - 3
      - 16
      - 23
      4: 3.7.13
      5: 0.13.2
      8:
      - 5
data:
  desc: null
  value: train_images
model:
  desc: null
  value: convnext_base
